# Generated by Django 4.0.3 on 2022-04-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('fungsi', models.TextField()),
                ('stok', models.IntegerField(default=0)),
                ('pemasok', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('officer', 'Officer')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='BarangMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.IntegerField(default=0)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.barang')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='BarangKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.IntegerField(default=0)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.barang')),
                ('pengambil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
    ]
