# Generated by Django 4.0.3 on 2022-04-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='barangkeluar',
            name='waktu',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='barangmasuk',
            name='waktu',
            field=models.DateField(auto_now_add=True),
        ),
    ]
