# Generated by Django 4.0.3 on 2022-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_barangkeluar_pengambil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangkeluar',
            name='waktu',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='barangmasuk',
            name='waktu',
            field=models.DateField(),
        ),
    ]
