# Generated by Django 4.0.3 on 2022-04-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_barang_stok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
